{% set name = "crystalmapping" %}
{% set version = "0.2.0" %}
{% set sha256 = "853b76721fe92c8e90d4ce77ef2992a4d0793aa8f1e6333e9194b48e82a424f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/st3107/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:

  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - bluesky
    - databroker
    - diffpy.structure
    - event-model
    - fire
    - numpy
    - ophyd
    - pyfai
    - seaborn
    - tifffile
    - tqdm
    - trackpy
    - xarray

test:
  requires:
    - python {{ python_min }}
  imports:
    - crystalmapping
    - crystalmapping.crystalmapper
    - crystalmapping.peakindexer

about:
  home: https://st3107.github.io/crystalmapping
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A python package to map the crystal morphology, crystallinity and crystal quality in boules.
  description: |
    The software is used to map the crystal morphology, crystallinity and crystal quality in boules that 
    were the product of an optical floating zone furnace (OFZF) growth. The input of the algorithm is a series of
    the diffraction images from a grid scan or a line scan using x-ray. There are Bragg diffraction spots on some 
    of the images, as shown in the Figure.~\ref{fig:algorithm}. Besides the diffraction data, users can also 
    provide the metadata of experiments including the shape and extents of the grid and the geometry of the
    experiment setup if they would like the software to index the images with positional parameters.
  doc_url: https://st3107.github.io/crystalmapping
  dev_url: https://github.com/st3107/crystalmapping

extra:
  recipe-maintainers:
    - sbillinge
    - st3107
